# Site settings
title: New Ways
header-img: img/home-bg.jpg
email: 
copyright_name:
description: "New Ways I have found and am exploring in varying areas of life."
baseurl: 
url: "http://kirstin.github.io"
twitter_username: tinir_ks
github_username:  kirstin
facebook_username:  Kirstin Heidler
email_username:  

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
